build:
    environment:
        elasticsearch: false
        memcached: false
        mongodb: false
        mysql: false
        neo4j: false
        postgresql: false
        rabbitmq: false
        redis: false

tools:
    external_code_coverage: true

checks:
    php:
        code_rating: true
