dist: trusty
language: php
sudo: required

php:
  - 7.1
  - 7.2
  - nightly

before_install:
  - echo "extension = snmp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update

before_script:
  - travis_retry composer update --prefer-dist

script: ./vendor/bin/phpunit

jobs:
  include:
    - stage: Coding Standard
      php: 7.1
      script: ./vendor/bin/phpcs

    - stage: Static Analysis
      php: 7.1
      script:
        - ./vendor/bin/phpstan analyse -c phpstan.neon.dist -l max src

cache:
  directories:
    - $HOME/.composer/cache

after_script:
  # upload clover.xml file to Scrutinizer to analyze it
  - |
    if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    if [ "$TRAVIS_PHP_VERSION" == "7.1" ]; then php ocular.phar code-coverage:upload --format=php-clover temp/clover.xml; fi
